language: python

python:
    - "3.6"

install:
    - pip install -U flake8
    - pip install -U flake8-bugbear
    - pip install -U flake8-docstrings
    - pip install -U pytest-cov

script:
    # static analysis
- flake8 .
- py.test --cov=. .
